### ISSUE TITLE
[Bug] Enable Proguard will causing exception `Service implementation is not found`

### ISSUE THREAD

**Issue by radityagumay** [line/lich#107]
Enabling Proguard which causing exceptions on the lich component. Please see stack traces below.

**Stack Traces**
```
04-22 08:50:50.240 25666 25666 E AndroidRuntime: Caused by:  com.linecorp.lich.component.FactoryDelegationException: Service implementation is not found.
04-22 08:50:50.240 25666 25666 E AndroidRuntime: 	at com.linecorp.lich.component.ComponentFactory.loadServiceLoaderComponent(Unknown Source:40)
04-22 08:50:50.240 25666 25666 E AndroidRuntime: 	at o.uhc$a.b(Unknown Source:20)
04-22 08:50:50.240 25666 25666 E AndroidRuntime: 	at o.uhc$a.createComponent(Unknown Source:10)
```

To fix the issue we need to add these rules which can be used for Proguard or Dexguard

```
-keep public class <class>.DefaultComponentProvider { *; }
-keep interface <class>.ComponentProvider { *; }
-keep public class * implements <class>.ServiceLoaderComponent { *; }
-if public class **.*$Companion extends <class>.ComponentFactory
-keep class <1>.<2> { *; }
```

**Comment by yamasa** [comment]
@radityagumay 
We strongly recommend to use R8 rather than ProGuard or DexGuard. R8 is the default shrinker for Android Gradle plugin 3.4.0 or higher.
https://developer.android.com/studio/build/shrink-code
By using R8, your code will work correctly without any special configuration.

If you really want to continue using ProGuard or DexGuard, add the following configuration to your proguard rules.
```
-keep public class * implements com.linecorp.lich.component.ServiceLoaderComponent {
    public <init>();
}
```

**Comment by radityagumay** [comment]
already tried that our earlier for, this is didn't work.

> -keep public class * implements com.linecorp.lich.component.ServiceLoaderComponent {
    public <init>();
}

this rules works for DexGuard

> -keep public class <class>.DefaultComponentProvider { *; }
-keep interface <class>.ComponentProvider { *; }
-keep public class * implements <class>.ServiceLoaderComponent { *; }
-if public class **.*$Companion extends <class>.ComponentFactory
-keep class <1>.<2> { *; }

**Comment by yamasa** [comment]
@radityagumay 
Thank you for the information.
Unfortunately, we do not plan to support DexGuard in our library. Please use R8 instead.

This problem is caused by the fact that DexGuard cannot handle classes that use `java.util.ServiceLoader`, so how about requesting the DexGuard developers to add the ability to handle ServiceLoader properly?
