### ISSUE TITLE
[Improvement] DefaultComponentProvider could be use AutoService instead of using META-INF

### ISSUE THREAD

**Issue by radityagumay** [line/lich#54]
In the current implementation, the `DefaultComponentProvider` is not utilizing AutoService to register the ServiceLocator. Adding manual registration always error-prone if we have multiple ServiceLocator components. In order to automate the process, we can install `AutoService` to `DefaultComponentProvider`

Potential changes from
```kotlin
internal class DefaultComponentProvider : ComponentProvider 
```

to
```kotlin
@AutoService(ComponentProvider::class)
internal class DefaultComponentProvider : ComponentProvider {
```

**Comment by yamasa** [comment]
To tell the truth, I don't like `AutoService` very much. Because it uses `kapt`, which increases build time significantly. So I would only like to use `AutoService` if it has enough benefits.

Lich Component is almost stable, and I plan to make only changes to follow updates of Android SDK / Kotlin in the future. Therefore, I don't think there is much benefit to introducing `AutoService` for Lich Component.

> Adding manual registration always error-prone

I agree, but Lich Component already has unit tests to prevent such errors.

**Comment by radityagumay** [comment]
@yamasa it's true but considering we're only adding 1 more class, and more further kotlin provides [KSP](https://github.com/google/ksp#kotlin-symbol-processing-api) to improve compilation build. 

But i agree with your point regarding stability in the current stages of the lich library
